-- PERMISSIONS: https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Changes here need a Hyprland restart. Everything is off by default.
-- hl.config({ ecosystem = { enforce_permissions = true } })
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")
